-- Multi-tenant shop profile, sales, and tenant columns on existing inventory tables.
-- Table names "Category" and "Product" match the Flutter Supabase client.

-- 1. Shop profile (tenant root, 1:1 with auth.users)
CREATE TABLE IF NOT EXISTS public.shop_profile (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    shop_name TEXT NOT NULL,
    whatsapp_number TEXT NOT NULL,
    telegram_username TEXT,
    description TEXT,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

-- 2. Link categories to a shop
ALTER TABLE public."Category"
ADD COLUMN IF NOT EXISTS "shopId" UUID REFERENCES public.shop_profile(id) ON DELETE CASCADE;

-- 3. Link products to a shop
ALTER TABLE public."Product"
ADD COLUMN IF NOT EXISTS "shopId" UUID REFERENCES public.shop_profile(id) ON DELETE CASCADE;

-- 4. Sale header
CREATE TABLE IF NOT EXISTS public.sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id UUID REFERENCES public.shop_profile(id) ON DELETE CASCADE NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    payment_method TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 5. Sale line items
CREATE TABLE IF NOT EXISTS public.sale_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES public.sale(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public."Product"(id) ON DELETE RESTRICT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    price_at_sale NUMERIC(10, 2) NOT NULL
);

-- 6. Row level security
ALTER TABLE public.shop_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_item ENABLE ROW LEVEL SECURITY;
